board_moim/urls.py
from django.urls import path
from . import views



app_name = 'board_moim'

urlpatterns = [
    path('', views.board_moim, name='board_moim'),
    path('list/', views.list_moim, name='list_moim'),
    path('<int:pk>/', views.board_detail, name='board_detail'),
    path('update/<int:pk>/', views.board_update, name='board_update'),
    path('delete/<int:pk>/', views.board_delete, name='board_detele'),
    path('comment/', views.comment, name='board_comment'),
    path('list/search/', views.search, name='search'),
    path('<int:pk>/kick/', views.kick, name='kick'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin', admin.site.urls), #admin, admin@admin.com, 1234
    path('write/', include('write.urls')),
    path('select_moim/', include('select_moim.urls')),
    path('make_moim/', include('make_moim.urls')),
    path('board_moim/', include('board_moim.urls')),
    path('profile/', include('all_info.urls')),
    path('login/', views.login,name='login'
    ),
    path('logout/', views.logout,name='logout'
    ),
    path('', views.home, name='home'
    ),
    path('search/', views.search, name='search'),#검색
    path('signup/', views.signup, name='signup'),#회원가입

    # path('loginfo/', include('loginfo.urls')),
    # path('login/',
    #     auth_views.LoginView.as_view(template_name='member/login.html'),
    #     name='login'
    # ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from . import views
app_name = 'file'
urlpatterns = [
path('upload/', views.upload, name='upload'),
path('upload_f/', views.upload_f, name='upload_f'),
]

all_info/models.py
from django.db import models

from make_moim.models import Make_Moim



class Info(models.Model):
    info_id = models.CharField(max_length = 20, primary_key=True)
    pw = models.CharField(max_length = 20, null=True)
    name = models.CharField(max_length = 20)
    region = models.CharField(max_length = 20)
    sex = models.CharField(max_length = 10)
    preference = models.CharField(max_length = 20)
    age = models.IntegerField(default=0)

class Category(models.Model):
    category = models.AutoField(primary_key=True)
    category_name = models.CharField(max_length = 20)
class Region(models.Model):
    region_id = models.AutoField(primary_key=True)
    region = models.CharField(max_length = 20, null=True)


# 김- 등산, 낚시. 책// 이 - 등산, 바둑  ...
class GroupInfo(models.Model):
    make_moim_info_id = models.AutoField(primary_key=True)
    info = models.ForeignKey(Info, on_delete=models.CASCADE,db_column='info_id', null=True)
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='make_id', null=True)
    y_n = models.CharField(max_length = 1)
    admin = models.IntegerField(default=0)
    apply_date = models.CharField(max_length = 20)
    join_date = models.CharField(max_length = 20)

board_moim/models.py
from django.db import models

# Create your models here.

tag/models.py
from django.db import models

from make_moim.models import Make_Moim

# Create your models here.

class Tag(models.Model):
    name = models.CharField(max_length=50, null=True)


    
class TagMoim(models.Model):
    tag_moim_id = models.AutoField(primary_key=True)
    tag = models.ForeignKey(Tag, on_delete=models.CASCADE,db_column='tag', null=True)
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='make_id', null=True)
    apply_date = models.CharField(max_length = 20)
    join_date = models.CharField(max_length = 20)

write/views.py
import time, os
from django.urls import reverse #이거 쓰나?
from django.shortcuts import  get_object_or_404,render, redirect

from config import settings
from make_moim.models import Make_Moim
from .forms import BoardWriteForm, GoodForm
from .models import Free, Gallery, Join ,Good, ManyImg
from all_info.models import Info
from django.views.generic import ListView, DetailView, CreateView #이것도 쓰나?
from django.http import HttpResponseRedirect , HttpResponse
from django.core.paginator import Paginator #얘 쓰나?
from django.core.files.storage import FileSystemStorage #얘도 쓰나?
# from django.view.decorators.http import require_http_methods

# def test(request):
#     board_list = Free.objects.all() #models.py Free 클래스의 모든 객체를 board_list에 담음
#     # board_list 페이징 처리
#     page = request.GET.get('page', '1') #GET 방식으로 정보를 받아오는 데이터
#     paginator = Paginator(board_list, '5') #Paginator(분할될 객체, 페이지 당 담길 객체수)
#     page_obj = paginator.page(page) #페이지 번호를 받아 해당 페이지를 리턴 get_page 권장
#     return render(request, 'template_name', {'page_obj':page_obj}) 


def text_delete(request,free_id, pk):#글삭
    login_session = request.session.get('info_id','')
    
    board = get_object_or_404(Free, free_id=pk)
    make_moim = Make_Moim.objects.get(make_id=free_id)

    if board.info.info_id == login_session:
        board.delete()
        return redirect('write:free', free_id)
    else:
        return redirect('write:free', free_id)

def text_modify(request,free_id, pk):#수정
    login_session = request.session.get('info_id','')
    make_moim = Make_Moim.objects.get(make_id=free_id)

    context = {'login_session' : login_session}

    board = get_object_or_404(Free, free_id=pk)
    context['board'] = board
    context['make_moim'] = make_moim

    if request.method == 'GET' :
        return render(request, 'write/modify.html', context)
    
    elif request.method =='POST':
        title = request.POST.get('title')
        text = request.POST.get('text')
        board.title=title
        board.text=text

        board.save()

        
        return redirect('write:free', free_id)


def view_text(request,free_id,pk): #게시물 보기
    free=Free.objects.get(free_id=pk)
    make_moim = Make_Moim.objects.get(make_id=free_id)
    return render(request, 'write/vt_free.html',{'free':free,'make_moim':make_moim })

def freeboard_index(request, free_id): #자유게인덱스
    all_boards = Free.objects.all().order_by("-write_dttm") # 모든 데이터 조회, 내림차순(-표시) 조회
    make_moim=Make_Moim.objects.get(make_moim=free_id)
    return render(request, 'write/freeindex.html', {'title':'Board List', 'board_list':all_boards})

def board_list(request):
    login_session = request.session.get('login_session','')
    context = {'login_session' : login_session}
    return render(request, 'base.html', context)

def board_free_write(request, free_id):#작성 
    login_session = request.session.get('info_id','')
    context = {'login_session' : login_session}

    make_moim = Make_Moim.objects.get(make_id=free_id)
    free=Free.objects.filter(make_moim=make_moim) #어떤 모임에서 써진 글들

    if request.method == 'GET' :
        write_form = BoardWriteForm
        context['forms'] = write_form
        context['make_moim']=make_moim
        return render(request, 'write/board_free_write.html', context)
    elif request.method =='POST':
        write_form = BoardWriteForm(request.POST, request.FILES)

        if write_form.is_valid():
            writer = Info.objects.get(info_id=login_session)
            board = Free(
                title=write_form.title,
                text=write_form.text,
                info=writer,
                imgfile=write_form.imgfile,
                make_moim=make_moim
                # comment=write_form.info
            )
            board.save()
            return redirect('write:free',free_id=free_id)
        
        else:
            context['forms'] = write_form
            context['make_moim']=make_moim
            if write_form.errors:
                for value in write_form.errors.values():
                    context['error'] = value
            return render(request, 'write/board_free_write.html',context)

    return render(request, 'write/board_free_write.html', context)

def free(request, free_id):
    
    make_moim=Make_Moim.objects.get(make_id=free_id)
    free_id = Free.objects.all().order_by('-pk')
    all_boards = Free.objects.all().order_by("-write_dttm")

    #페이징
    page = int(request.GET.get('page',1))
    # if not page : page = '1'
    # page=int(page)
    end = page * 10
    start = end - 10
    s_page = (page-1)//10*10 + 1
    e_page = s_page +9

    #페이지 구분
    total_count = Free.objects.all().count()
    total_page = total_count//10 +1
    if page > total_page:
        page = total_page
        end = page * 10
        start = end -10
    
    if total_count % 10 !=0:
        total_page +=1

    if e_page > total_page : 
        e_page = total_page

    page_info = range(s_page, e_page)
    all_boards = all_boards[start:end]

    context = {
        'all_boards' : all_boards,
        'page_info' : page_info,
        'total_page' : total_page,
        'e_page' : e_page,
        'page':page,
        'make_moim':make_moim,
        'free': free_id, 'board_list':all_boards,
        # 'posts' : posts
    }

    return render(
        request,
        'write/free.html',
        context
    )

def join(request):
    join_id = Join.objects.all().order_by('-pk')
    
    return render(
        request,
        'write/join.html',
        {'join': join_id}
    )

def new_face(request):
    new_face_id = Join.objects.all().order_by('-pk')
    
    return render(
        request,
        'write/new_face.html',
        {'new_face': new_face_id}
    )
def gallery(request, pk):
    make_moim=Make_Moim.objects.get(make_id=pk)
    gallery_list = Gallery.objects.all().order_by('-gallery_id')

    #페이징
    page = int(request.GET.get('page',1))
    # if not page : page = '1'
    # page=int(page)
    end = page * 5
    start = end - 5
    s_page = (page-1)//10*10 + 1
    e_page = s_page +9

    #페이지 구분
    total_count = Gallery.objects.all().count()
    total_page = total_count//5 +1
    if page > total_page:
        page = total_page
        end = page * 5
        start = end -5
    
    if total_count % 5 !=0:
        total_page +=1

    if e_page > total_page : 
        e_page = total_page

    page_info = range(s_page, e_page)
    gallery_list = gallery_list[start:end]

    context = {
        'gallery_list' : gallery_list,
        'page_info' : page_info,
        'total_page' : total_page,
        'e_page' : e_page,
        'page':page,
        'make_moim':make_moim,
        # 'posts' : posts
    }

    return render(
        request,
        'write/gallery_list.html',
        context
    )

def gallery_makeit(request, pk):
    make_moim=Make_Moim.objects.get(make_id=pk)        
    if request.method == 'GET':
            return render(request, 'write/gallery_makeit.html',{'make_moim':make_moim})
    else :
        try:
            info_id=request.session['info_id']
            id=Info.objects.get(info_id=info_id)

            # writer=request.POST.get('id')
            # Gallery.objects.filter(info=writer)

            # comments = Good.objects.filter(gallery=make_moim)#댓글임
            
            
            title = request.POST.get('title')
            comment = request.POST.get('contents')
            imgfiles = request.FILES.getlist('imgfiles')
            make_moim = request.POST.get('make_moim')


            gallery=Gallery(title=title, comment=comment , info=id, make_moim=Make_Moim.objects.get(pk=make_moim), )
            gallery.save()

            for upload_file in imgfiles:
                name = upload_file.name
                name=name.replace('.',f'{int(time.time())}.')
        
                # a.jpg -> (중복) a_unixtime.jpg
                #                a_167375584983.jpg
                with open('media/gallery/'+name, 'wb') as file:
                    
                    for chunk in upload_file.chunks():
                        # manyimg=ManyImg.objects.filter(gallery=(int(last_gallery)+1))
                        #게시글 최신->이미지1,이미지2,이미지3....
            

                        file.write(chunk)
                manyimg=ManyImg.objects.create(imgfile=name, gallery=gallery)
                manyimg.save()
            #multiple도 get으로 받나?
            #info-프라이머리키라서 어차피 1개->writer로 직접 저장 가능
        
        except Exception as e:
            print(e)
            return redirect('/login/')
    return redirect('write:gallery' ,pk)

def gallery_make(request): #이게머지???/
    gallery = Gallery.objects.all().order_by('-pk')

    if request.method == 'POST':
        #회원정보 조회
        files = request.POST.get('files')
        text = request.POST.get('text')
        title = request.POST.get('title')
        
        
        try:
            info = request.session['info']
            info_id=Info.objects.get(info_id=info)
            new_gallery = Gallery()
            new_gallery.comment =text
            new_gallery.title = title
            new_gallery.imgfile = files
            new_gallery.save()
            return HttpResponseRedirect('write:gallery')
        except:
            return render(request, 'login_fail.html')
    return render(request, 'gallery_makeit.html')

def gallery_single(request, pk, gg): #FBV로 싱글갤러리 만들기
    gallery_singles = Gallery.objects.get(gallery_id=gg)
    make_moim = Make_Moim.objects.get(make_id=pk)
    manyimg=ManyImg.objects.filter(gallery=gallery_singles)

    return render(request, 'write/single_gallery.html', {'single_gallery':gallery_singles, 'make_moim':make_moim, 'manyimg':manyimg})

def gallery_delete(request, pk, gg): #FBV로 싱글갤러리 만들기
    gallery_singles = Gallery.objects.get(gallery_id=gg)
    make_moim = Make_Moim.objects.get(make_id=pk)
    writer=request.POST.get('writer')
    id=request.session['info_id']
    if id==writer:

board_moim/templates/board_moim/board_list.html
<head>
{% include 'head.html' %}
</head>

<body>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
      
      </div>
    </div>
  </section>

  <!-- ======= Header ======= -->
{% include 'header_main.html' %}

  <main id="main">


    <!-- ======= Ctab Section ======= -->
    <section class="inner-page">
      <div class="container">
        <section id="ctab" class="ctab">
          <div class="container">
            {% block main_content %}
            <div>
              <tbody>
          {% for m in moim_lists%}
          <div>
          <a href="/board_moim/{{m.make_id}}/" style='color: blue;'>자세히보기</a>
          <label for="id"></label>
          <input type="hidden" name='id' value="{{m.make_id}}" readonly>

          <label for="category">카테고리 : </label>
          <input type="text" name='category' value="{{m.category}}" readonly style="border: 0;">

          <hr>
          <b style="font-size: xx-small;">태그 : 
            {% for t in m.tagmoim_set.all %}
               {{t.tag.name}}
              <input type="hidden" name='tag' value="{{t.tag.name}}">
            {% endfor %}</b>
          <hr>
          <label for="name"></label>
          <input type="text" name='name' value="{{m.name}}" readonly style="border: 0; font-size: larger;" >
          <label for="commend"></label>
          <textarea class="form-control" row='4' cols='50' style=''>모임소개 : {{m.commend}}</textarea>
          <br>
          <br>
          <br>
          {% if m.imgfile %}
          <label for="imgfile"></label>
          <img src="/media/{{m.imgfile}}" alt="{{m.name}} " style= 'width : 300px'>
          {% else %}
          <label for="imgfile">이미지</label>
          <img src="/static/default.jpg" alt="{{m.name}} " style= 'width : 300px'>
          {% endif %}
      <br>
          <label for="location" style="border: 0; font-size: larger;">지역/최대인원/현재인원</label>
          <br>
          <input type="text" name='location' value="{{m.location}}/       {{m.max_people}}        /       {{m.groupinfo_set.count}}" readonly style="border: 0;">
      

          <hr>
          </div>
      
      
          {% endfor %}
      </tbody>
      </div>
      <tbody>
          <ul>
          {% if page > 10 %}
              <a href="/board_moim/list/?page={{page | add:'-10'}}">이전</a>
          {% endif %}
          {% for p in page_info %}
              {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
              <a href="/board_moim/list/?page={{p}}">
              {{p}}
              </a></li>
          {% endfor %}
          {% if total_page > e_page %}
              <a href="/board_moim/list/?page={{page | add:'10'}}">다음</a>
          {% endif %}
          </ul>
      
      </tbody>
          {% csrf_token %}
            {% endblock %}

          </div>
        </section><!-- End Ctab Section -->
      </div>
    </section>


  <!-- 검색기능 -->
  <div>
    {% include 'board_moim/search_bar.html' %}
  </div>  
  
  </main><!-- End #main -->


  <!-- ======= Footer ======= -->
{% include 'footer_main.html' %}

  <!-- Vendor JS Files -->
  <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/assets/js/main.js"></script>

</body>

</html>

board_moim/templates/board_moim/search.html
<head>
{% include 'head.html' %}
</head>

<body>

    <!-- ======= Top Bar ======= -->
    <section id="topbar" class="d-flex align-items-center">
        <div class="container d-flex justify-content-center justify-content-md-between">
            <div class="contact-info d-flex align-items-center">

            </div>
        </div>
    </section>

    <!-- ======= Header ======= -->
    {% include 'header_main.html' %}

    <main id="main">


        <!-- ======= Ctab Section ======= -->
        <section class="inner-page">
            <div class="container">
                <section id="ctab" class="ctab">
                    <div class="container">
                        {% block main_content %}
                        <div>
                            <tbody>
                                <h1> {{search}} 검색 결과</h1>
                                {% if make_moim and category and tag %}
                                <br>
                                <hr>
                                {% include 'board_moim/search_n_c.html' %}

                                {% include 'board_moim/search_tag.html' %}

                                <!-- 이 아래에 추가  -->
                                {% for m in category_list%}
                                <div>
                                    <a href="/board_moim/{{m.make_id}}/">자세히보기</a>
                                    <label for="id"></label>
                                    <input type="hidden" name='id' value="{{m.make_id}}" readonly>
                                    <hr>

                                    <label for="category">카테고리</label>
                                    <input type="text" name='category' value="{{m.category}}" readonly>

                                    <hr>
                                    <b>태그 :
                                        {% for t in m.tagmoim_set.all %}
                                        {{t.tag.name}}
                                        <input type="hidden" name='tag' value="{{t.tag.name}}">
                                        {% endfor %}</b>
                                    <hr>
                                    <label for="name">제목</label>
                                    <input type="text" name='name' value="{{m.name}}" readonly>

                                    <br>
                                    {% if m.imgfile %}
                                    <label for="imgfile">이미지</label>
                                    <img src="/media/{{m.imgfile}}" alt="{{m.name}} " style='width : 300px'>
                                    {% else %}
                                    <label for="imgfile">이미지</label>
                                    <img src="/static/default.jpg" alt="{{m.name}} " style='width : 300px'>
                                    {% endif %}

                                    <label for="location">지역/최대인원/현재인원</label>
                                    <input type="text" name='location'
                                        value="{{m.location}}/{{m.max_people}}/{{m.groupinfo_set.count}}" readonly>

                                    <label for="commend">소개</label>
                                    <textarea class="form-control" readonly>{{m.commend}}</textarea>
                                    <hr>
                                </div>


                                {% endfor %}
                            </tbody>
                        </div>
                        <tbody>
                            <ul>
                                {% if page_ctg > 10 %}
                                <a href="/board_moim/list/search/?page_ctg={{page_ctg | add:'-10'}}">이전</a>
                                {% endif %}
                                {% for p in page_info_ctg %}
                                {% comment %} <li {% if p==page_ctg %} active {% endif %}> {% endcomment %}
                                    <a href="/board_moim/list/search/?page_ctg={{p}}">
                                        {{p}}
                                    </a>
                                </li>
                                {% endfor %}
                                {% if category_page > e_page_ctg %}
                                <a href="/board_moim/list/search/?page_ctg={{page_ctg | add:'10'}}">다음</a>
                                {% endif %}
                            </ul>

                        </tbody>


                        {% elif make_moim or category %}


                        <br>
                        <hr>
                        {% include 'board_moim/search_n_c.html' %}
                        {% elif tag %}


                        <br>
                        <hr>
                        {% include 'board_moim/search_tag.html' %}


                        {% else %}
                        <h1>검색 결과가 없습니다. 새로 검색해주세요</h1>
                        {% endif %}
                        {% csrf_token %}
                        </tbody>
                        {% endblock %}

                    </div>
                </section><!-- End Ctab Section -->
            </div>
        </section>


        <!-- 검색기능 -->
        <div>
            {% include 'board_moim/search_bar.html' %}
        </div>

    </main><!-- End #main -->


    <!-- ======= Footer ======= -->
    {% include 'footer_main.html' %}

    <!-- Vendor JS Files -->
    <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
    <script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
    <script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
    <script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
    <script src="/static/assets/vendor/php-email-form/validate.js"></script>

    <!-- Template Main JS File -->
    <script src="/static/assets/js/main.js"></script>

</body>

</html>

board_moim/templates/board_moim/search_bar.html
<div class="search-bar">
    <form class="search-form d-flex align-items-center" method="POST" action="/board_moim/list/search/">
        {% csrf_token %}
        <select style="border: none" name="search_b" id="search_b" onchange="changeValue(value)">
          <option value="all">전체검색</option>
          <option value="search_title">제목</option>
          <option value="tag_title">태그</option>
          <option value="category_title">카테고리</option>
        </select>
      <input type="hidden" name="change_search_bar" id="change_search_bar" value="all">
      <input type="text" name="search" placeholder="Search" title="Enter search keyword">
      <button type="submit" title="Search"><i class="bi bi-search"></i></button>
    </form>
  </div><!-- End Search Bar -->




  
  <script>
    const change_search_bar=document.getElementById('change_search_bar');
    const changeValue = function(value){
      console.log('값변경테스트 : ' + value);
      change_search_bar.value = value;
    }

    /*const search_bar = document.getElementById('search_b')
    const change_search_bar =  document.getElementById(`change_search_bar`).value
    change_search_bar.addEventListener('change', (e)=>{
      const options = e.currentTarget.options;
      const index = e.currentTarget.options.selectedIndex;
      change_search_bar.name = `${options[index]}`;
    })    
    console.log(change_search_bar)*/


  </script>

board_moim/templates/board_moim/search_n_c.html
{% for m in total_list%}
          <div>
          <a href="/board_moim/{{m.make_id}}/" style="color: blue;">자세히보기</a>
          <label for="id"></label>
          <input type="hidden" name='id' value="{{m.make_id}}" readonlystyle='border: 0;'>
<hr>
          <label for="category">카테고리 : </label>
          <input type="text" name='category' value="{{m.category}}" style='border: 0;' readonly>

          <hr>
          <b style="font-size: xx-small;">태그 : 
            {% for t in m.tagmoim_set.all %}
               {{t.tag.name}}
              <input type="hidden" name='tag' value="{{t.tag.name}}">
            {% endfor %}</b>
          <hr>
          <label for="name">제목 : </label>
          <input type="text" name='name' value="{{m.name}}" readonly style='border: 0;'>
      
          <br>
          {% if m.imgfile %}
          <label for="imgfile"></label>
          <img src="/media/{{m.imgfile}}" alt="{{m.name}} " style= 'width : 300px'>
          {% else %}
          <label for="imgfile"></label>
          <img src="/static/default.jpg" alt="{{m.name}} " style= 'width : 300px'>
          {% endif %}
            <hr>
          <label for="location">지역/최대인원/현재인원</label>
          <hr>
          <input type="text" name='location' value="{{m.location}}/{{m.max_people}}/{{m.groupinfo_set.count}}" readonly>
          <hr>
      
          <label for="commend"></label>
          <textarea class="form-control" readonly>소개 : {{m.commend}}</textarea>
          <hr>
          </div>
      
      
          {% endfor %}
      </tbody>
      </div>
      <tbody>
          <ul>
          {% if page > 10 %}
              <a href="/board_moim/list/search/?page={{page | add:'-10'}}">이전</a>
          {% endif %}
          {% for p in page_info %}
              {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
              <a href="/board_moim/list/search/?page={{p}}">
              {{p}}
              </a></li>
          {% endfor %}
          {% if total_page > e_page %}
              <a href="/board_moim/list/search/?page={{page | add:'10'}}">다음</a>
          {% endif %}
          </ul>
      
      </tbody>

board_moim/templates/board_moim/search_tag.html
{% for m in tag_list.tagmoim_set.all%}
          <div>
          <a href="/board_moim/{{m.make_moim.make_id}}/">자세히보기</a>
          <label for="id">번호</label>
          <input type="text" name='id' value="{{m.make_moim.make_id}}" readonly>

          <label for="category">카테고리</label>
          <input type="text" name='category' value="{{m.make_moim.category}}" readonly>

          <hr>
          <b>태그 : 
            {% for t in tag_list %}
               {{t.tag.name}}
              <input type="hidden" name='tag' value="{{t.tag.name}}">
            {% endfor %}</b>
          <hr>
          <label for="name">제목</label>
          <input type="text" name='name' value="{{m.make_moim.name}}" readonly>
      
          <br>
          {% if m.make_moim.imgfile %}
          <label for="imgfile">이미지</label>
          <img src="/media/{{m.make_moim.imgfile}}" alt="{{m.make_moim.name}} " style= 'width : 300px'>
          {% else %}
          <label for="imgfile">이미지</label>
          <img src="/static/default.jpg" alt="{{m.make_moim.name}} " style= 'width : 300px'>
          {% endif %}
      
          <label for="location">지역/최대인원/현재인원</label>
          <input type="text" name='location' value="{{m.make_moim.location}}/{{m.make_moim.max_people}}/{{m.make_moim.groupinfo_set.count}}" readonly>
      
          <label for="commend">소개</label>
          <textarea class="form-control" readonly>{{m.make_moim.commend}}</textarea>
          <hr>
          </div>
      
      
          {% endfor %}
      </tbody>
      </div>
      <tbody>
          <ul>
          {% if page_tag > 10 %}
              <a href="/board_moim/list/search/?page_tag={{page_tag | add:'-10'}}">이전</a>
          {% endif %}
          {% for p in page_info_tag %}
              {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
              <a href="/board_moim/list/search/?page_tag={{p}}">
              {{p}}
              </a></li>
          {% endfor %}
          {% if tag_page > e_page_tag %}
              <a href="/board_moim/list/search/?page_tag={{page_tag | add:'10'}}">다음</a>
          {% endif %}
          </ul>
      
      </tbody>

board_moim/templates/board_moim/update_fail.html
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>수정에 실패했습니다.</title>
    <script>
        var result = confirm("수정에 실패하셨습니다")
        window.opener.location.reload();  
        window.close();    

        location = "update/{{make_moim.make_id}}/"

       
    </script>
</head>
<body>
</body>
</html>