config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin', admin.site.urls), #admin, admin@admin.com, 1234
    path('write/', include('write.urls')),
    path('select_moim/', include('select_moim.urls')),
    path('make_moim/', include('make_moim.urls')),
    path('board_moim/', include('board_moim.urls')),
    path('profile/', include('all_info.urls')),
    path('login/', views.login,name='login'
    ),
    path('logout/', views.logout,name='logout'
    ),
    path('', views.home, name='home'
    ),
    path('search/', views.search, name='search'),#검색
    path('signup/', views.signup, name='signup'),#회원가입

    # path('loginfo/', include('loginfo.urls')),
    # path('login/',
    #     auth_views.LoginView.as_view(template_name='member/login.html'),
    #     name='login'
    # ),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

file/urls.py
from django.urls import path
from . import views
app_name = 'file'
urlpatterns = [
path('upload/', views.upload, name='upload'),
path('upload_f/', views.upload_f, name='upload_f'),
]

write/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views



app_name = 'write'

urlpatterns = [
    path('free/<int:free_id>/', views.free, name='free'),
    # path('join/', views.join, name='join'),
    
    path('join/<int:make_id>/', views.join_detail, name='join_detail'),
    path('join/<int:make_id>/comment/', views.join_comment, name='join_comment'),

    path('join/<int:make_id>/comment/update/', views.join_comment_u, name='join_comment_u'),
    path('join/<int:make_id>/comment/delete/', views.join_comment_d, name='join_comment_d'),

    path('join/join_write/', views.join, name='join_write'),
    path('gallery/<int:pk>/', views.gallery, name='gallery'),
    path('gallery/<int:pk>/<int:gg>/', views.gallery_single, name='gallery_single'),
    
    path('gallery/<int:pk>/<int:gg>/delete/', views.gallery_delete, name='gallery_delete'),
    path('gallery/<int:pk>/<int:gg>/modify/', views.gallery_modify, name='gallery_modify'),
    path('gallery/<int:pk>/<int:gg>/modify2/', views.gallery_modify2, name='gallery_modify2'),
    path('gallery/<int:pk>/<int:gg>/modify2/delete/', views.gallery_img_delete, name='gallery_img_delete' ),
    path('gallery/<int:pk>/<int:gg>/modify3/', views.gallery_modify3, name='gallery_modify3' ),
    path('download/', views.download, name='download' ),

    path('new_face/', views.new_face, name='new_face'),
    path('gallery/<int:pk>/gallery_makeit/', views.gallery_makeit, name='gallery_makeit'),
    path('', views.board_list, name='board_list'),
    # path('borad_left/', views.borad_left, name='borad_left'),
    path('free/<int:free_id>/free_write/', views.board_free_write, name='free_write'),
    path('<int:pk>/comments/', views.comments_create, name='comments_create'),

    path('join/<int:make_id>/delete/', views.join_delete, name='join_delete' ),
    path('join/<int:make_id>/modify/', views.join_modify, name='join_modify' ),
    path('join/<int:make_id>/modify2/', views.join_modify2, name='join_modify2' ),


    # path('gallery/<int:pk>/', views.gallery_detail, name='gallery_detail'),
    path('comments/<int:free_id>/<int:comment_pk>/delete/', views.comments_delete, name='comments_delete'),
    # path('<int:free_pk>/likes/', views.likes, name='likes'),
    path('freeboard_index/<int:free_id>/', views.freeboard_index, name='freeindex'),#자유게인덱스
    path('viewtext/<int:free_id>/<int:pk>/', views.view_text, name='free01' ),#view text, vt 게시물보기
    path('viewtext/<int:free_id>/<int:pk>/delete/', views.text_delete, name='delete' ),
    path('viewtext/<int:free_id>/<int:pk>/modify/', views.text_modify, name='modify' ),

    path('free/<int:pk>/search/', views.free_search, name='free_search'),#검색
    path('gallery/<int:pk>/search/', views.gallery_search, name='gallery_search'),#검색
] 
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

write/models.py
from django.conf import settings
from django.db import models

from all_info import models as models2
from make_moim.models import Make_Moim
from select_moim.models import Select_Moim  # 좋아요-import setting


# Create your models here. 
class Join(models.Model):
    join_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=200, null=True)
    comment = models.CharField(max_length=200, null=True)
    info = models.ForeignKey(models2.Info, on_delete=models.CASCADE,db_column='info_id', null=True)
    write_dttm = models.DateTimeField(auto_now_add=True, null=True)
    update_dttm = models.DateTimeField(auto_now=True, null=True)
    new_face = models.TextField(verbose_name='가입인사', null=True)
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='moim_id', null=True)
    def __str__(self):
        return f'[{self.pk}][{self.title}]'

class Free(models.Model): #
    free_id = models.AutoField(primary_key=True)
    text = models.TextField(verbose_name='글 내용', null=True)
    comment = models.CharField(max_length=200, null=True)
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles') #좋아요 추가
    info = models.ForeignKey(models2.Info, on_delete=models.CASCADE,db_column='info_id', null=True)
    title = models.CharField(max_length=64, verbose_name='글 제목', default='')
    write_dttm = models.DateTimeField(auto_now_add=True, null=True)
    update_dttm = models.DateTimeField(auto_now=True, null=True)
    hits=models.PositiveIntegerField(default=0)
    imgfile = models.ImageField(null=True, upload_to="", blank=True) # 이미지 컬럼 추가
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='moim_id', null=True)
    # make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='moim_id', null=True)
    # select_moim = models.ForeignKey(Select_Moim, on_delete=models.CASCADE,db_column='select_id', null=True)
    def __str__(self):
        return f'[{self.pk}][{self.title}]'

class Gallery(models.Model): #FBV로 만듬
    gallery_id = models.AutoField(primary_key=True)
    title = models.CharField(max_length=64, verbose_name='글 제목', default='')
    comment = models.CharField(max_length=200, null=True)
    picture = models.CharField(max_length=200, null=True)
    write_dttm = models.DateTimeField(auto_now_add=True, null=True)
    update_dttm = models.DateTimeField(auto_now=True, null=True)
    info = models.ForeignKey(models2.Info, on_delete=models.CASCADE,db_column='info_id', null=True)
    imgfile = models.ImageField(null=True, upload_to="gallery/%Y%m%d", blank=True) # 이미지 컬럼 추가
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE,db_column='moim_id', null=True)
    select_moim = models.ForeignKey(Select_Moim, on_delete=models.CASCADE,db_column='select_id', null=True)
    
    def __str__(self):
        return f'[{self.pk}][{self.title}]'

class Good(models.Model):#댓글 연결
    good_id = models.AutoField(primary_key=True)
    free = models.ForeignKey(Free, on_delete=models.CASCADE,db_column='free_id', null=True)
    info = models.ForeignKey(models2.Info, on_delete=models.CASCADE,db_column='info_id', null=True)
    join = models.ForeignKey(Join, on_delete=models.CASCADE,db_column='join_id', null=True)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE,db_column='gallery_id', null=True)
    select_moim = models.ForeignKey(Select_Moim, on_delete=models.CASCADE,db_column='select_id', null=True)
    content = models.CharField(max_length=200, null=True) #댓글
    # title = models.CharField(max_length=200, null=True) #제목
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    updated_at = models.DateTimeField(auto_now=True, null=True)
    make_moim = models.ForeignKey(Make_Moim, on_delete=models.CASCADE, null=True)
    def __str__(self):
        return self.content

class ManyImg(models.Model): #이미지 여러개 업로드할려면?
    manyimg_id = models.AutoField(primary_key=True)
    gallery = models.ForeignKey(Gallery, on_delete=models.CASCADE,db_column='gallery_id', null=True)
    save_path = models.CharField(max_length=50, null=True)
    save_name = models.CharField(max_length=50, null=True)
    imgfile = models.ImageField(null=True, upload_to="gallery/%Y%m%d", blank=True) # 이미지 컬럼 추가

write/forms.py
from django import forms
from .models import Free, Good
from all_info.models import Info
from django_summernote.fields import SummernoteTextField
from django_summernote.widgets import SummernoteWidget

class BoardWriteForm(forms.ModelForm): #자유게시판용 게시판 만들기
    title = forms.CharField(
        label='글 제목',
        widget=forms.TextInput(
            attrs={
                'placeholder':'게시글 제목'
            }
        )
    )
    contents = SummernoteTextField


    #여기 아래에 select로 게시판 종류 추가하기
    options = (
        ('Free','자유게시판'),
        ('Free2','자유게시판2'),
        ('Free3','자유게시판3')

    )

    board_name = forms.ChoiceField(
        label='게시판 선택',
        widget=forms.Select(),
        choices=options
    )

    field_order  = [
        'title',
        'text',
        'imgfile',
        # 'info'
    ]

    class Meta:
        model = Free
        fields = [
            'title',
            'text',
            'imgfile',
            # 'info'
        ]
        widgets = {
            'contents' : SummernoteWidget()
        }
    def clean(self):
        cleaned_data = super().clean()

        title = cleaned_data.get('title','')
        text = cleaned_data.get('text','')
        imgfile = cleaned_data.get('imgfile','')
        # info = cleaned_data.get('info','Free')

        if title == '':
            self.add_error('title','글 제목을 입력하세요.')
        elif text =='':
            self.add_error('text','글 내용을 입력하세요')
        else:
            self.title = title
            self.text = text
            self.imgfile = imgfile
            # self.info = info
            
class GoodForm(forms.ModelForm): #댓글 작성시 필드 보이지 않게
    class Meta :
        model = Good
        # fields = '__all__'
        exclude = ('free', 'info', 'gallary', 'join')
        

write/templates/write/board_free_write.html
{% comment %} {% extends 'home/index.html'%} {% endcomment %}
{% comment %} {% block contents %} {% endcomment %}
<div>게시판 글쓰기!</div>
<form action="/write/free/{{make_moim.make_id}}/free_write/" method="POST" enctype="multipart/form-data>

    {% for form in forms %}
    {% csrf_token %}

    <div>
        <label for="{{ form.id_for_label}}">{{form.label}}</label>
        
        {{form}}
    </div>
    {% endfor %}

    {% if error %}
    {{ error}}
    {% endif %}
    <button>작성</button>
</form>
{% comment %} {% endblock contents %} {% endcomment %}

write/templates/write/detail.html
<h4>댓글 목록</h4>

<!--read-->
{% if comments %}
  <p><b>{{ comments|length }}개의 댓글이 있습니다.</b></p>
{% endif %}
<ul>
  {% for comment in comments %}
    <li>
      {{ comment.user }} - {{ comment.content }}
      <!--delete-->
      {% if user == comment.user %}
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST" class="d-inline">
          {% csrf_token %}
          <input type="submit" value="DELETE">
        </form>
      {% endif %}
    </li>
  {% empty %}
    <p>댓글이 없습니다.</p>
  {% endfor %}
</ul>

<hr>

<!--create-->
{% if request.user.is_authenticated %}
  <form action="{% url 'articles:comments_create' article.pk %}" method="POST">
    {% csrf_token %}
    {{ comment_form }}
    <input type="submit">
  </form>
{% else %}
  <a href="{% url 'accounts:login' %}">[댓글을 작성하려면 로그인하세요.]</a>
{% endif %}
{% endblock content %}

write/templates/write/free.html
{% extends 'homecopy.html' %} 
{% block left_menu %}
{% endblock left_menu %}
{% block main_content %}
<body>
<tbody>
<section id="breadcrumbs" class="breadcrumbs">
    <div class="container" >
    <div class="d-flex justify-content-between align-items-center" >
          <h2>목록</h2>
          <ol>
            <li><a href="/select_moim/{{make_moim.make_id}}/">{{make_moim}}</a></li>
            <li>자유게시판</li>
          </ol>
        </div>
    </div>
</section>

{% include 'write/freeindex.html' %}
<div><a href="/write/free/{{make_moim.make_id}}/free_write/"><button>글쓰기</button></a></div>
</tbody>
<tbody>
    <ul>
    {% if page > 10 %}
        <a href="/write/free/{{make_moim.make_id}}/?page={{page | add:'-10'}}">이전</a>
    {% endif %}
    {% for p in page_info %}
        {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
        <a href="/write/free/{{make_moim.make_id}}/?page={{p}}">
        {{p}}
        </a></li>
    {% endfor %}
    {% if total_page > e_page %}
        <a href="/write/free/{{make_moim.make_id}}/?page={{page | add:'10'}}">다음</a>
    {% endif %}
    </ul>

</tbody>
{% include 'write/search_bar_free.html'%}
</body>
{% endblock  %}

</html>

write/templates/write/free1.html
{% extends 'homecopy.html' %} 
{% block left_menu %}
{% endblock left_menu %}
{% block main_content %}
<body>

<div>게시판</div>
{% include 'write/freeindex.html' %}
<div><a href="{% url 'write:free_write' %}"><button>글쓰기</button></a></div>
    
</body>
{% endblock  %}

write/templates/write/gallery.html
{% extends 'homecopy.html' %} 
{% block left_menu %}
{% endblock left_menu %}
{% block main_content %}
    <h1>갤러리입니다.</h1>
    <div><a href="/write/gallery/gallery_makeit"><button>글쓰기</button></a></div>
    <div>
        <table>
            <tr>
                <td>이미지</td>
                <td>내용</td>
                <td>자세히보기</td>
                <td>작성자</td>
                <td>작성시간</td>
            </tr>
            {{gallery_text}}
            {% include 'write/gallery_list.html' %}</td>
        </table>
    </div>
{% endblock  %}

write/templates/write/gallery_free_write.html
{% comment %} {% extends 'home/index.html'%} {% endcomment %}
{% comment %} {% block contents %} {% endcomment %}
<div>갤러리 글쓰기!</div>
<form action="" method="POST">
    <!-- {% csrf_token %} -->

    {% for form in forms %}
    <div>
        <label for="{{ form.id_for_label}}">{{form.label}}</label>
        {{form}}
    </div>
    {% endfor %}

    {% if error %}
    {{ error}}
    {% endif %}
    <button>작성</button>
</form>
{% comment %} {% endblock contents %} {% endcomment %}

write/templates/write/gallery_list.html
<!DOCTYPE html>
<html lang="ko">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Inner Page - Green Bootstrap Template</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Favicons -->
  <link href="/static/assets/img/favicon.png" rel="icon">
  <link href="/static/assets/img/apple-touch-icon.png" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Raleway:300,300i,400,400i,500,500i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">

  <!-- Vendor CSS Files -->
  <link href="/static/assets/vendor/animate.css/animate.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/bootstrap-icons/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/assets/vendor/boxicons/css/boxicons.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/glightbox/css/glightbox.min.css" rel="stylesheet">
  <link href="/static/assets/vendor/swiper/swiper-bundle.min.css" rel="stylesheet">

  <!-- Template Main CSS File -->
  <link href="/static/assets/css/style.css" rel="stylesheet">

  <!-- =======================================================
  * Template Name: Green - v4.10.0
  * Template URL: https://bootstrapmade.com/green-free-one-page-bootstrap-template/
  * Author: BootstrapMade.com
  * License: https://bootstrapmade.com/license/
  ======================================================== -->
</head>

  <!-- ======= Top Bar ======= -->
  <section id="topbar" class="d-flex align-items-center">
    <div class="container d-flex justify-content-center justify-content-md-between">
      <div class="contact-info d-flex align-items-center">
      
      </div>
    </div>
  </section>

<body>
  <!-- ======= Header ======= -->
  {% include 'select_header.html' %}
  <!-- End Header -->

  <!-- ======= Sidebar ======= -->
  {% include 'leftbar.html' %}
  <!-- End Sidebar-->
  
  <main id="main">


    <!-- ======= Ctab Section ======= -->
    <section class="inner-page">
      <div class="container">
        <section id="ctab" class="ctab">
          <div class="container">
            {% block main_content %}
            <tbody>
                {% if gallery_list %}
                    {% for g in gallery_list %}
                        <hr>
                        <td><h2 onclick='location="/write/gallery/{{make_moim.make_id}}/{{g.gallery_id}}/"'>제목 : {{g.title}}</h2></td>
                        <hr>
                        {% for imgfile in g.manyimg_set.all %}
                        <td><img src="/media/gallery/{{imgfile.imgfile}}/" alt="사진이 지워졌습니다." style = 'width: 80px';></td>            
                        {% endfor %}
                        <hr>
                        <td>내용 : {{g.comment}}</td>
                        <br>
                        <td>작성자 : {{g.info.info_id}}</td>
                        <td>작성일자 :{{g.write_dttm}}</td>
                        </tr>
                        <hr>
                
                    {% endfor %}
                {% else %}
                        <h1>{{make_moim.name}} 갤러리</h1>
                        <h1>작성된 글이 없습니다.</h1>
                {% endif %}
                <a href="/write/gallery/{{make_moim.make_id}}/gallery_makeit/">
                    <button type="submit" name="img" style="margin-bottom: 200px;">사진올리기</button></a>
                </a>
                </tbody>
                <tbody>
                    <ul>
                    {% if page > 10 %}
                        <a href="/write/gallery/{{make_moim.make_id}}/?page={{page | add:'-10'}}">이전</a>
                    {% endif %}
                    {% for p in page_info %}
                        {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
                        <a href="/write/gallery/{{make_moim.make_id}}/?page={{p}}">
                        {{p}}
                        </a></li>
                    {% endfor %}
                    {% if total_page > e_page %}
                        <a href="/write/gallery/{{make_moim.make_id}}/?page={{page | add:'10'}}">다음</a>
                    {% endif %}
                    </ul>
                
                </tbody>
                {% include 'write/search_bar_gallery.html'%}
                
            {% endblock %}
          </div>
        </section><!-- End Ctab Section -->
      </div>
    </section>

  </main><!-- End #main -->

  <!-- ======= Footer ======= -->
  <footer id="footer">
    <div class="container">
      <h3>Green</h3>
      <p>Et aut eum quis fuga eos sunt ipsa nihil. Labore corporis magni eligendi fuga maxime saepe commodi placeat.</p>
      <div class="social-links">
        <a href="#" class="twitter"><i class="bx bxl-twitter"></i></a>
        <a href="#" class="facebook"><i class="bx bxl-facebook"></i></a>
        <a href="#" class="instagram"><i class="bx bxl-instagram"></i></a>
        <a href="#" class="google-plus"><i class="bx bxl-skype"></i></a>
        <a href="#" class="linkedin"><i class="bx bxl-linkedin"></i></a>
      </div>
      <div class="copyright">
        &copy; Copyright <strong><span>Green</span></strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!-- All the links in the footer should remain intact. -->
        <!-- You can delete the links only if you purchased the pro version. -->
        <!-- Licensing information: https://bootstrapmade.com/license/ -->
        <!-- Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/green-free-one-page-bootstrap-template/ -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- End Footer -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>
  <a href="#" class="back-to-down d-flex align-items-center justify-content-center"><i class="bi bi-arrow-down-short"></i></a>

  <!-- Vendor JS Files -->
  <script src="/static/assets/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>
  <script src="/static/assets/vendor/glightbox/js/glightbox.min.js"></script>
  <script src="/static/assets/vendor/isotope-layout/isotope.pkgd.min.js"></script>
  <script src="/static/assets/vendor/swiper/swiper-bundle.min.js"></script>
  <script src="/static/assets/vendor/php-email-form/validate.js"></script>

  <!-- Template Main JS File -->
  <script src="/static/assets/js/main.js"></script>

</body>

</html>

write/templates/write/join.html
<body>

    <div>가입인사</div>
    <div><a href="{% url 'write:join_write' %}"><button>글쓰기</button></a></div>
    {% comment %} 좋아요추가!! {% endcomment %}
    <div>
        <form action="{% url 'join:likes' pk=join.pk %}" method='POST'>
          {% csrf_token %}
          {% if user in join.like_users.all %}
            <input type="submit" value='좋아요 취소'>
          {% else %}
            <input type="submit" value='좋아요'>
          {% endif %}
        </form>
    </div>
</body>

write/templates/write/join_comment.html
<div>
    <span style="font-size: xx-small;" onclick="test()">이전 댓글로 이동</span>
    <hr>
    {% for g in goods %}
    △<br>
    <p>
    내용 : {{g.content}}

    <span style="font-size: xx-small;">
        작성자 : {{g.info.info_id}}
        작성시간 : {{g.created_at}}
        댓글번호 : {{g.join.join_id}}
    </span>
    </p>
    <form action="/write/join/{{make_moim.make_id}}/comment/update/" method="post">
        <input type="hidden" name="writer" value="{{g.info.info_id}}">
        <input type="hidden" name="good_id" value="{{g.good_id}}">
        <input type="text" name="content" value="{{g.content}}">
        <button name="new_update" style="border: 0; background-color: white;">
        {% csrf_token %} 수정, 
    </button></form>
    <form action="/write/join/{{make_moim.make_id}}/comment/delete/" method="post">
        <input type="hidden" name="writer" value="{{g.info.info_id}}">
        <input type="hidden" name="good_id" value="{{g.good_id}}">
        <input type="hidden" name="content" value="{{g.content}}">
        <button name="new_update" style="border: 0; background-color: white;">
        {% csrf_token %} 삭제, 
    </button></form>
    {% endfor %}

</div>

<script>
    function doNotReload(){
        if(    (event.ctrlKey == true && (event.keyCode == 78 || event.keyCode == 82))
            || (event.keyCode == 116) )
        {
        event.keyCode = 0;
        event.cancelBubble = true;
        event.returnValue = false;
        alert("새로고침 방지");
        }
    }
    document.onkeydown = doNotReload;
    function test() {
        history.back();
    }
    </script>
    <body oncontextmenu="return false">

write/templates/write/join_detail.html
{% extends 'homecopy.html' %} 
{% block left_menu %}
{% include 'write/board_menu2.html' %}
{% endblock left_menu %}
{% block main_content %}
<div>
</div>
</tbody>
<tbody>
    <ul>
    {% if page > 10 %}
        <a href="/write/join/{{make_moim.make_id}}/?page={{page | add:'-10'}}">이전</a>
    {% endif %}
    {% for p in page_info %}
        {% comment %} <li {% if p == page %} active {% endif %}> {% endcomment %}
        <a href="/write/join/{{make_moim.make_id}}/?page={{p}}">
        {{p}}
        </a></li>
    {% endfor %}
    {% if total_page > e_page %}
        <a href="/write/join/{{make_moim.make_id}}/?page={{page | add:'10'}}">다음</a>
    {% endif %}
    </ul>

</tbody>

<tbody>
<div>
    {% for t in join_list %}
    <div>
        
        <h6> {{t.title}} </h6>
        <p> {{t.comment}} </p>
        <h6> {{t.info.info_id}} </h6>
        <h6> {{t.write_dttm}} </h6>
        <form action="/write/join/{{make_moim.make_id}}/modify/" method="post">{% csrf_token %}<button value="수정" name="update">수정</button>        
        <input type="hidden" name="writer" value="{{t.info.info_id}}">
        <input type="hidden" name="join_id" value="{{t.join_id}}"></button>
        </form>
        <form action="/write/join/{{make_moim.make_id}}/delete/" method="post">{% csrf_token %}<button value="삭제" name="delete">삭제       
        <input type="hidden" name="writer" value="{{t.info.info_id}}">
        <input type="hidden" name="join_id" value="{{t.join_id}}"></button>
        </form>
        <button id='reply' name='reply'>답글</button>
        <br>
        <form action="/write/join/{{make_moim.make_id}}/comment/" method="post">
        <span style="font-size: xx-small;" onclick="location='comment/'" >
            <input type="hidden" name="join_id" value="{{t.join_id}}">
            {% csrf_token %}
            <button name="btn" style="border:0; background-color: white;">댓글상세보기</button>
        </span></form>
        {% include "write/join_comment.html" %}
        <hr>
        <div name="a" id='a' style="display: block;"></div>
        <div name="b" id='b' style="display: none;">
        <form action="/write/join/{{make_moim.make_id}}/comment/" method="post"><input type="text" name="reply_comment">
            <input type="hidden" name="join_id" value="{{t.join_id}}">
            {% csrf_token %}
            <button>답글</button></form>
        </div>
    </div>
    {% endfor %}
</div>
<div>

    <form action="/write/join/{{make_moim.make_id}}/" method="post">
        {% csrf_token %}
    <h1>모임 : {{make_moim.name}}</h1>
    <h5>"{{request.session.info_id}}" 님의 인사창입니다.</h5>
    제목 : <input type="text" name="title">
    <br>
    <input type="hidden" name="writer" value='{{request.session.info_id}}' readonly>
    <textarea class="form-control" name="comment">내용</textarea>
    <input type="hidden" name='make_moim' value="{{make_moim.make_id}}">
    <button>등록</button>
    </form>
    <hr>

</div>
<script>

    const reply = document.getElementById('reply')
    const allbtn = document.querySelectorAll(`#reply`)
    const aa = document.querySelectorAll(`#a`)
    const bb = document.querySelectorAll(`#b`)
    console.log(bb[0].style.display)
    console.log(bb[2])
    console.log(aa[0].style.display)
    console.log(aa[1])
    console.log(allbtn[2])
    console.log(allbtn[0])


    /* 여기부분 어떻게 인접 선택자?? */
    for (let i =0; i < allbtn.length; i++){
        allbtn[i].addEventListener('click', (e) =>{ 

            /*const a = document.getElementById(`a`)
            const b = document.getElementById(`b`)*/
            if (bb[i].style.display == 'none'){
                aa[i].style.display = 'none';
                bb[i].style.display = 'block';
            }else{
                aa[i].style.display = 'block';
                bb[i].style.display = 'none';
            }
        })
    }
</script>
{% endblock  %}